# Generated by Django 5.0.1 on 2024-02-01 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_bankrupt_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='bankrupt',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='transactions.bankrupt'),
            preserve_default=False,
        ),
    ]
