# Generated by Django 5.0.1 on 2024-02-01 20:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_transaction_bankrupt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='bankrupt',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.bankrupt'),
        ),
    ]
