# Generated by Django 5.0.1 on 2024-02-01 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_bankrupt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bankrupt',
        ),
        migrations.DeleteModel(
            name='Bankrupt',
        ),
    ]
