# Generated by Django 5.0.1 on 2024-02-01 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_bankrupt_transaction_bankrupt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='bankrupt',
            new_name='is_bankrupt',
        ),
    ]
